version: "2"

services:
  octaaf:
    image: golang:1.10
    volumes:
        - .:/go/src/octaaf
    working_dir: /go/src/octaaf
    command: ./init.sh
    network_mode: host
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
      - jaeger

  redis:
    image: redis:4.0
    ports:
      - "6379:6379"

  postgres:
    image: postgres:10.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "octaaf_development"
      POSTGRES_USER: "octaaf"

  jaeger:
    image: jaegertracing/all-in-one:1.7
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: "9411"
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
